version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4-jessie-node
    steps:
      - run: sudo apt-get install tox
      - run: sudo npm install -g less
      - checkout
      - run: tox
