version: 2
jobs:
  build:
    docker:
      - image: hdoomsday/python-nodejs:3.6
      - checkout
  3_6:
    docker:
      - image: hdoomsday/python-nodejs:3.6
    steps:
      - run: sudo pip install tox
      - run: sudo npm install -g less
      - run: tox -e py36
  3_5:
    docker:
      - image: hdoomsday/python-nodejs:3.5
    steps:
      - run: sudo pip install tox
      - run: sudo npm install -g less
      - run: tox -e py35
  2_7:
    docker:
      - image: hdoomsday/python-nodejs:2.7
    steps:
      - run: sudo pip install tox
      - run: sudo npm install -g less
      - run: tox -e py27
  coverage:
    docker:
      - image: hdoomsday/python-nodejs:3.6
    steps:
      - run: sudo pip install coveralls
      - run: sudo npm install -g less
      - run:
          name: Run coverage
          command: |
            coverage run --source=cellar setup.py test
            coveralls
          environment:
            COVERALLS_REPO_TOKEN: qJaHs6LtKVUC2SJcnDev0acWLtPuW1vXM
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - 2_7:
          requires:
            - build
      - 3_5:
          requires:
            - build
      - 3_6:
          requires:
            - build
      - coverage:
          requires:
            - 2_7
            - 3_5
            - 3_6
