version: 2
jobs:
  build:
    docker:
      - image: hdoomsday/python-nodejs:3.6
    steps:
      - checkout
  py36:
    docker:
      - image: hdoomsday/python-nodejs:3.6
    steps:
      - run: sudo pip install tox
      - run: sudo npm install -g less
      - checkout
      - run: tox -e py36
  py35:
    docker:
      - image: hdoomsday/python-nodejs:3.5
    steps:
      - run: sudo pip install tox
      - run: sudo npm install -g less
      - checkout
      - run: tox -e py35
  py27:
    docker:
      - image: hdoomsday/python-nodejs:2.7
    steps:
      - run: sudo pip install tox
      - run: sudo npm install -g less
      - checkout
      - run: tox -e py27
  coverage:
    docker:
      - image: hdoomsday/python-nodejs:3.6
    steps:
      - run: sudo pip install coveralls
      - run: sudo npm install -g less
      - checkout
      - run:
          name: Run coverage
          command: |
            coverage run --source=cellar setup.py test
            coveralls
          environment:
            COVERALLS_REPO_TOKEN: qJaHs6LtKVUC2SJcnDev0acWLtPuW1vXM
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - py27:
          requires:
            - build
      - py35:
          requires:
            - build
      - py36:
          requires:
            - build
      - coverage:
          requires:
            - py27
            - py35
            - py36
