version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4-jessie-node
    steps:
      - run: sudo pip install tox coveralls
      - run: sudo npm install -g less
      - checkout
      - run: tox
      - run:
          name: Run coverage
          command: |
            coverage run --source=cellar setup.py test
            coveralls
          environment:
            COVERALLS_REPO_TOKEN: qJaHs6LtKVUC2SJcnDev0acWLtPuW1vXM
